name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme CodeScanner
    - name: Build ( mac Catalyst 12.0)
      run: xcodebuild build -scheme CodeScanner -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst'
    - name: Build ( iOS 15.0)
      run: xcodebuild build -scheme CodeScanner -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'